tx-object-store not empty after running TestATSubordinateCrashDuringPrepare XTS recovery test
The following assertion fails when the test completes with transaction logs stil present in the tx-object-store.

{code}
-------------------------------------------------------------------------------
Test set: com.arjuna.qa.junit.TestATSubordinateCrashDuringPrepare
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 79.706 sec <<< FAILURE!
subordinateMultiParticipantPrepareAndCommitTest(com.arjuna.qa.junit.TestATSubordinateCrashDuringPrepare)  Time elapsed: 79.694 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at com.arjuna.qa.junit.BaseCrashTest.tearDown(BaseCrashTest.java:94)
{code}

See:
http://172.17.131.2/view/XTS%20recovery/job/narayana-xts-recovery-java6/28/
